# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jinli Duan
title: Computer Engineering, M.S. Candidate
email: jd5374@nyu.edu
website: www.github.com/your_github_username_here  # Replace with your GitHub username if you have one

# Dark Mode (true/false/never)
darkmode: false

# Social links
# Add your social media usernames or comment out the ones you don't use
twitter_username: your_twitter_username_here
github_username:  your_github_username_here
instagram_username: your_instagram_username_here
linkedin_username: your_linkedin_username_here
youtube_username: your_youtube_username_here

# Additional icon links
# Add any additional links you want to display
# - title: Link title
#   icon: font awesome brand icon name
#   url: Link url

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Jinli Duan, a Computer Engineering M.S. candidate at New York University with a background in Software Engineering from the University of California, Irvine. Skilled in Java, Python, C++, and various other technologies. Native speaker of Mandarin and proficient in English.

content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: New York University
        sub_title: Computer Engineering, M.S.
        caption: June 2022-2024
        description: |
          Relevant Coursework: Machine Learning, Deep learning, Internet Architecture etc.

      - layout: left
        title: University of California, Irvine
        sub_title: Software Engineering, B.S.
        caption: June 2018-2022
        description: |
          Relevant Coursework: Python, Database, C++, Java, Linear Algebra etc.
          Former vice president of Astronomy club at UCI.

      - layout: left
        title: Covenant Christian High School
        sub_title: Academic Honors Diploma
        caption: Jan 2014-2018
        description: |
          AP physics C, AP Calculus AB/BC.

  - title: Skills
    layout: text
    content: |
      Computer: Java/Python/C++ Js/Node.js/CSS/HTML MIPS UI/UX design MySql/Postgresql/MongoDB etc
      Language: Chinese(Mandarin):Native speaker, English: proficient

  - title: Honors
    layout: list
    content:
      - layout: left
        title: National Honor Society
        caption: 2017-2018

      - layout: left
        title: Academic Scholarship
        caption: 2022-2024

      - layout: left
        title: Dean’s list
        caption: 2021-2022

  - title: Internship
    layout: list
    content:
      # ... Add all your internships here in a similar format ...

  - title: Projects
    layout: list
    content:
      # ... Add all your projects here in a similar format ...

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
